language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
    - os: linux
      dist: bionic
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode11.6

before_script:
  - cmake --version
  - env

script:
  - mkdir build && cd build && cmake .. && cmake --build . && ctest
